"""add_routes_table_and_activity_route_fk

Revision ID: 1288ec48e3dc
Revises: 
Create Date: 2025-05-06 17:55:00.000000 

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1288ec48e3dc'
down_revision: Union[str, None] = 'f98fe1fc0fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gpx_file_content', sa.Text(), nullable=False, comment='Raw GPX XML content'),
    sa.Column('source_type', sa.Enum('gpx_upload', 'from_activity', name='routesourcetype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_name'), 'routes', ['name'], unique=False)
    
    op.add_column('activities', sa.Column('route_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_activities_route_id'), 'activities', ['route_id'], unique=False)
    op.create_foreign_key(
        'fk_activities_route_id_routes',  # Constraint name
        'activities', 'routes',
        ['route_id'], ['id'],
        ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_activities_route_id_routes', 'activities', type_='foreignkey')
    op.drop_index(op.f('ix_activities_route_id'), table_name='activities')
    op.drop_column('activities', 'route_id')
    
    op.drop_index(op.f('ix_routes_name'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    
    # Downgrade for the Enum type if it was created
    sa.Enum(name='routesourcetype').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
