"""added recap models

Revision ID: e01dc994960b
Revises: 4ac2cc4f4e41
Create Date: 2025-05-02 13:48:42.008693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e01dc994960b'
down_revision: Union[str, None] = '4ac2cc4f4e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('summary_type', sa.Enum('WEEKLY', 'MONTHLY', 'YEARLY', name='summarytype'), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=False),
    sa.Column('total_duration', sa.Float(), nullable=False),
    sa.Column('total_elevation_gain', sa.Float(), nullable=False),
    sa.Column('total_calories', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_summaries_activity_type'), 'activity_summaries', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activity_summaries_end_date'), 'activity_summaries', ['end_date'], unique=False)
    op.create_index(op.f('ix_activity_summaries_id'), 'activity_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_activity_summaries_start_date'), 'activity_summaries', ['start_date'], unique=False)
    op.create_index(op.f('ix_activity_summaries_summary_type'), 'activity_summaries', ['summary_type'], unique=False)
    op.create_index(op.f('ix_activity_summaries_user_id'), 'activity_summaries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_summaries_user_id'), table_name='activity_summaries')
    op.drop_index(op.f('ix_activity_summaries_summary_type'), table_name='activity_summaries')
    op.drop_index(op.f('ix_activity_summaries_start_date'), table_name='activity_summaries')
    op.drop_index(op.f('ix_activity_summaries_id'), table_name='activity_summaries')
    op.drop_index(op.f('ix_activity_summaries_end_date'), table_name='activity_summaries')
    op.drop_index(op.f('ix_activity_summaries_activity_type'), table_name='activity_summaries')
    op.drop_table('activity_summaries')
    # ### end Alembic commands ###
